export const footerLinks = [
    {
      title: "وسائل التواصل الاجتماعي",
      links: [
        { title: "ديسكورد", url: "/" },
        { title: "إنستغرام", url: "/" },
        { title: "تويتر", url: "/" },
        { title: "فيسبوك", url: "/" },
      ],
    },
    {
      title: "شركة",
      links: [
        { title: "الأحداث", url: "/" },
        { title: "مدونة", url: "/" },
        { title: "بودكاست", url: "/" },
        { title: "ادعُ صديقًا", url: "/" },
      ],
    },
  
    {
      title: "عن",
      links: [
        { title: "كيف يعمل", url: "/" },
        { title: "مميز", url: "/" },
        { title: "شراكة", url: "/" },
        { title: "علاقة عمل", url: "/" },
      ],
    },
  ];

  export const category = [
    {
      id: 1,
      title: "موبايلات و تابلت",
      link1: "موبايلات",
      link2: "تابلت",
      link3: " كل مافي موبايلات و تابلت ",
      Link1:"/",
      Link2:"/",
      Link3:"/",
      img: "https://cdn-icons-png.flaticon.com/128/545/545245.png",
    },
    {
      id: 2,
      title: "عقارات",
      link1: "شقق للبيع",
      link2: "شقق للإيجار",
      link3: "كل مافي عقارات",
      Link1:"/real-estate/houses-sale",
      Link2:"/real-estate/houses-sale",
      Link3:"/real-estate",
      img: "https://cdn-icons-png.flaticon.com/128/8743/8743467.png",
    },
    {
      id: 3,
      title: "سيارات",
      link1: "سيارات للبيع",
      link2: "سيارات للإيجار",
      link3: "كل مافي السيارات",
      Link1:"/cars/cars-sale",
      Link2:"/cars/cars-rent",
      Link3:"/cars",
      img: "https://cdn-icons-png.flaticon.com/128/2962/2962303.png",
    },
  ];
  export const villasSale = [
    {
      id: 1515,
      price: "3,000,000,000",
      description: "فيلا للبيع استلام فوري تبعد 7 دقائق عن دمشق في افضل موقع",
      layout: "325",
      bed: "2",
      bathroom: "4",
      date: 71,
      location: "دمشق, طريق المطار",
      img: "https://images.pexels.com/photos/206172/pexels-photo-206172.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 2665,
      price: "4,500,000,000",
      description: "فيلا للبيع استلام فوري ",
      layout: "425",
      bed: "4",
      bathroom: "8",
      date: 7,
      location: "دمشق, طريق المطار",
      img: "https://images.pexels.com/photos/53610/large-home-residential-house-architecture-53610.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 5165,
      price: "2,000,000,000",
      description: "فيلا للبيع استلام فوري ",
      layout: "325",
      bed: "2",
      bathroom: "3",
      date: 6,
      location: "دمشق",
      img: "https://images.pexels.com/photos/816198/pexels-photo-816198.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 644989,
      price: "2,000,000,000",
      description: "فيلا للبيع استلام فوري تبعد 7 دقائق عن دمشق في افضل موقع",
      layout: "325",
      bed: "2",
      bathroom: "3",
      date: 6,
      img: "https://images.pexels.com/photos/36355/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=600",
    },
  ];
  export const villasRent = [
    {
      id: 1655,
      price: "1,000,000",
      description: "فيلا للإيجار استلام فوري تبعد 15 دقائق عن دمشق في افضل موقع",
      layout: "325",
      bed: "2",
      bathroom: "4",
      date: 6,
      location: "ريف دمشق, معلولا",
      img: "https://images.pexels.com/photos/261101/pexels-photo-261101.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 2548,
      price: "1,500,000",
      description: "فيلا للإيجار استلام فوري تبعد 7 دقائق عن دمشق في افضل موقع",
      layout: "425",
      bed: "4",
      bathroom: "8",
      date: 6,
      img: "https://images.pexels.com/photos/261327/pexels-photo-261327.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 3489,
      price: "2,000,000",
      description: "فيلا للإيجار استلام فوري تبعد 7 دقائق عن دمشق في افضل موقع",
      layout: "325",
      bed: "2",
      bathroom: "3",
      date: 6,
      img: "https://images.pexels.com/photos/2480608/pexels-photo-2480608.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 4548,
      price: "7,000,000",
      description: "فيلا للإيجار استلام فوري تبعد 7 دقائق عن دمشق في افضل موقع",
      layout: "325",
      bed: "2",
      bathroom: "3",
      date: 6,
      img: "https://images.pexels.com/photos/1438834/pexels-photo-1438834.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
  ];
  export const houseSale = [
    {
      id: 1455,
      price: "9000,000",
      description: "منزل للبيع وسط دمشق ",
      layout: "100",
      bed: "2",
      bathroom: "3",
      date: 6,
      img: "https://images.pexels.com/photos/280222/pexels-photo-280222.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 2565,
      price: "75000,000",
      description: " منزل للبيع في حي القنواة",
      layout: "75",
      bed: "1",
      bathroom: "2",
      date: 6,
      location: "دمشق, حي القنواة",
      img: "https://images.pexels.com/photos/206172/pexels-photo-206172.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 3548,
      price: "1,000,000,0",
      description: "منزل للبيع في حي الزاهرة",
      layout: "100",
      bed: "1",
      bathroom: "3",
      date: 6,
      location: "دمشق, حي الزاهرة",
      img: "https://images.pexels.com/photos/2724749/pexels-photo-2724749.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 4884,
      price: "800,0000",
      description: "منزل للبيع في ريف دمشق ,الغوطة الشرقية",
      layout: "120",
      bed: "1",
      bathroom: "4",
      date: 6,
      location: "  ريف دمشق, الغوطة الشرقية ",
      img: "https://images.pexels.com/photos/2079234/pexels-photo-2079234.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
  ];
  export const houseRent = [
    {
      id: 1565,
      price: "9000,0",
      description: "منزل للإيجار وسط دمشق ",
      layout: "100",
      bed: "2",
      bathroom: "3",
      date: 6,
      img: "https://images.pexels.com/photos/280222/pexels-photo-280222.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 4898,
      price: "750000",
      description: " منزل للإيجار في حي القنواة",
      layout: "75",
      bed: "1",
      bathroom: "2",
      date: 6,
      location: "دمشق, حي القنواة",
      img: "https://images.pexels.com/photos/206172/pexels-photo-206172.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 4848,
      price: "1,000,000",
      description: "منزل للإيجار في حي الزاهرة",
      layout: "100",
      bed: "1",
      bathroom: "3",
      date: 6,
      location: "دمشق, حي الزاهرة",
      img: "https://images.pexels.com/photos/2724749/pexels-photo-2724749.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 1561,
      price: "800,0000",
      description: "منزل للإيجار في ريف دمشق ,الغوطة الشرقية",
      layout: "120",
      bed: "1",
      bathroom: "4",
      date: 6,
      location: "  ريف دمشق, الغوطة الشرقية ",
      img: "https://images.pexels.com/photos/2079234/pexels-photo-2079234.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
  ];
  export const carSale = [
    {
      id: 1258,
      price: "90,0000",
      description: "فورد فيوجن  ",
      date: 2,
      speed: "25000",
      production: "2021",
      location: "",
      engine:"2000",
      fuel:"بانزين",
      transmission:"اوتوماتيك",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRoRJ8RvC7P5QOumwfaPhPERZzmbasE-M3bBw&s",
    },
    {
      id: 2321,
      price: "90,0000",
      description: "رينو اوسترال",
      date: 4,
      speed: "20000",
      production: "2020",
      location: "ريف دمشق, ببيلا",
      engine:"2000",
      fuel:"مازون",
      transmission:"اوتوماتيك",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMnq2APGr_l6dFxk5o5R26dGVy79IwTd2RLA&s",
    },
    {
      id: 3698,
      price: "90,0000",
      description: "مازدا 6 نص فل خليجي 2025",
      date: 5,
      speed: "0",
      production: "2025",
      location: "دمشق, شارع بغداد",
      engine:"2500",
      fuel:"بانزين",
      transmission:"عادي",
      img: "https://alemaratcars.com/wp-content/uploads/2024/08/%D9%85%D8%A7%D8%B2%D8%AF%D8%A7-6-%D9%86%D8%B5-%D9%81%D9%84-2025.jpg",
    },
    {
      id: 4789,
      price: "90,0000",
      description: "هيونداي سانتفيه",
      date: 7,
      speed: "70000",
      production: "2013",
      location: "دمشق, شارع خالد بن الوليد",
      engine:"1600",
      fuel:"مازوت",
      transmission:"اوتوماتيك",
      img: "https://www.bankstreethyundai.com/vimgs/CAC30HYS041B021001/IOF_H600/2013-Hyundai-Santa-Fe-4dr-FWD-SWB_101.jpg",
    },
  ];
  export const carRent = [
    {
      id: 1258,
      price: "90,0000",
      description: "فورد فيوجن  ",
      date: 2,
      speed: "25000",
      production: "2021",
      location: "",
      engine:"2000",
      fuel:"مازوت",
      transmission:"اوتوماتيك",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRoRJ8RvC7P5QOumwfaPhPERZzmbasE-M3bBw&s",
    },
    {
      id: 2589,
      price: "90,0000",
      description: "رينو اوسترال",
      date: 4,
      speed: "20000",
      production: "2020",
      location: "ريف دمشق, ببيلا",
      engine:"1600",
      fuel:"بانزين",
      transmission:"عادي",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMnq2APGr_l6dFxk5o5R26dGVy79IwTd2RLA&s",
    },
    {
      id: 3963,
      price: "90,0000",
      description: "مازدا 6 نص فل خليجي 2025",
      date: 5,
      speed: "0",
      production: "2025",
      location: "دمشق, شارع بغداد",
      engine:"2500",
      fuel:"بانزين",
      transmission:"اوتوماتيك",
      img: "https://alemaratcars.com/wp-content/uploads/2024/08/%D9%85%D8%A7%D8%B2%D8%AF%D8%A7-6-%D9%86%D8%B5-%D9%81%D9%84-2025.jpg",
    },
    {
      id: 4874,
      price: "90,0000",
      description: "هيونداي سانتفيه",
      date: 7,
      speed: "70000",
      production: "2013",
      location: "دمشق, شارع خالد بن الوليد",
      engine:"2000",
      fuel:"بانزين",
      transmission:"اوتوماتيك",
      img: "https://www.bankstreethyundai.com/vimgs/CAC30HYS041B021001/IOF_H600/2013-Hyundai-Santa-Fe-4dr-FWD-SWB_101.jpg",
    },
  ];
  export const mobile =[
    {
      id:4155 ,
      price:1255,
      description:"ايفون 15 برو ماكس ذاكرة 256 جيجا 5G تيتانيوم طبيعي",
      date: 9,
      location: "دمشق",
      img:"https://media.zid.store/ece77ccf-86ab-4963-877d-4a5f24928aa9/a86707d7-1c9b-40ba-bb31-73e49e2c2be1.jpg"
    },
    {
      id:1236,
      price:15548,
      description:"  موبايل سامسونج جالاكسي A16 شريحتين 128 جيجا 6 جيجا رمادي",
      date: 6,
      location: "ريف دمشق, معلولا",
      img:"https://lh3.googleusercontent.com/proxy/eMs2kVLRXVlKogxQjvW35WqfmE6yqGpjkByMwV3nNloi7aQOAvdSyzFNNbfj7QAGr3YLBCy2VFwl2_hCvMLZtefRTeL-Vf0_D4IoiEGHFfPa5DwXllmGQI2YbWhfc3wwOhV9euXCvOaQlf7z2A"
    },
    {
      id:2589,
      price:54548,
      description:" لون اسود  GB/4GB 64 مواصفات x200 w&o موبايل",
      date: 8,
      location:"",
      img:"https://mesrshop.com/wp-content/uploads/2024/09/W-O-X200-Ultra-thin-4G-Smartphones-Quad-Core-4GB-64GB-6-53Inch-HD-Display-Android_11zon.webp"
    },
    {
      id:3465,
      price:4548,
      description:"سامسونج جالكسي S24 الترا 256GB + 12GB , لون بنفسجي تيتانيوم",
      date: 6,
      location:"",
      img:"https://media.zid.store/thumbs/b74f2313-1275-4caa-abca-b5ece66cb8bd/0f1b1422-1ca0-4c8b-b995-004c3dede361-thumbnail-1000x1000.png"
    },
  ]