export const footerLinks = [
    {
      title: "وسائل التواصل الاجتماعي",
      links: [
        { title: "ديسكورد", url: "/" },
        { title: "إنستغرام", url: "/" },
        { title: "تويتر", url: "/" },
        { title: "فيسبوك", url: "/" },
      ],
    },
    {
      title: "شركة",
      links: [
        { title: "الأحداث", url: "/" },
        { title: "مدونة", url: "/" },
        { title: "بودكاست", url: "/" },
        { title: "ادعُ صديقًا", url: "/" },
      ],
    },
  
    {
      title: "عن",
      links: [
        { title: "كيف يعمل", url: "/" },
        { title: "مميز", url: "/" },
        { title: "شراكة", url: "/" },
        { title: "علاقة عمل", url: "/" },
      ],
    },
  ];

  export const category = [
    {
      id: 1,
      title: "عقارات",
      link1: "شقق للبيع",
      link2: "شقق للإيجار",
      link: "كل مافي عقارات",
  
      img: "https://cdn-icons-png.flaticon.com/128/8743/8743467.png",
    },
    {
      id: 2,
      title: "موبايلات و تابلت",
      link1: "موبايلات",
      link2: "تابلت",
      link: " كل مافي موبايلات و تابلت ",
  
      img: "https://cdn-icons-png.flaticon.com/128/545/545245.png",
    },
    {
      id: 3,
      title: "سيارات",
      link1: "سيارات للبيع",
      link2: "سيارات للإيجار",
      link: "كل مافي السيارات",
  
      img: "https://cdn-icons-png.flaticon.com/128/2962/2962303.png",
    },
  ];
  export const villasSale = [
    {
      id: 156615,
      price: "3,000,000,000",
      description: "فيلا للبيع استلام فوري تبعد 7 دقائق عن دمشق في افضل موقع",
      layout: "325",
      bed: "2",
      bathroom: "4",
      date: 71,
      location: "دمشق, طريق المطار",
      img: "https://images.pexels.com/photos/206172/pexels-photo-206172.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 2565665,
      price: "4,500,000,000",
      description: "فيلا للبيع استلام فوري ",
      layout: "425",
      bed: "4",
      bathroom: "8",
      date: 7,
      location: "دمشق, طريق المطار",
      img: "https://images.pexels.com/photos/53610/large-home-residential-house-architecture-53610.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 55616165,
      price: "2,000,000,000",
      description: "فيلا للبيع استلام فوري ",
      layout: "325",
      bed: "2",
      bathroom: "3",
      date: 6,
      location: "دمشق",
      img: "https://images.pexels.com/photos/816198/pexels-photo-816198.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 644989,
      price: "2,000,000,000",
      description: "فيلا للبيع استلام فوري تبعد 7 دقائق عن دمشق في افضل موقع",
      layout: "325",
      bed: "2",
      bathroom: "3",
      date: 6,
      img: "https://images.pexels.com/photos/36355/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=600",
    },
  ];
  export const villasRent = [
    {
      id: 16565,
      price: "1,000,000",
      description: "فيلا للإيجار استلام فوري تبعد 15 دقائق عن دمشق في افضل موقع",
      layout: "325",
      bed: "2",
      bathroom: "4",
      date: 6,
      location: "ريف دمشق, معلولا",
      img: "https://images.pexels.com/photos/261101/pexels-photo-261101.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 25448,
      price: "1,500,000",
      description: "فيلا للإيجار استلام فوري تبعد 7 دقائق عن دمشق في افضل موقع",
      layout: "425",
      bed: "4",
      bathroom: "8",
      date: 6,
      img: "https://images.pexels.com/photos/261327/pexels-photo-261327.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 3648489,
      price: "2,000,000",
      description: "فيلا للإيجار استلام فوري تبعد 7 دقائق عن دمشق في افضل موقع",
      layout: "325",
      bed: "2",
      bathroom: "3",
      date: 6,
      img: "https://images.pexels.com/photos/2480608/pexels-photo-2480608.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 454848,
      price: "7,000,000",
      description: "فيلا للإيجار استلام فوري تبعد 7 دقائق عن دمشق في افضل موقع",
      layout: "325",
      bed: "2",
      bathroom: "3",
      date: 6,
      img: "https://images.pexels.com/photos/1438834/pexels-photo-1438834.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
  ];
  export const houseSale = [
    {
      id: 1455,
      price: "9000,000",
      description: "منزل للبيع وسط دمشق ",
      layout: "100",
      bed: "2",
      bathroom: "3",
      date: 6,
      img: "https://images.pexels.com/photos/280222/pexels-photo-280222.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 255565,
      price: "75000,000",
      description: " منزل للبيع في حي القنواة",
      layout: "75",
      bed: "1",
      bathroom: "2",
      date: 6,
      location: "دمشق, حي القنواة",
      img: "https://images.pexels.com/photos/206172/pexels-photo-206172.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 356548,
      price: "1,000,000,0",
      description: "منزل للبيع في حي الزاهرة",
      layout: "100",
      bed: "1",
      bathroom: "3",
      date: 6,
      location: "دمشق, حي الزاهرة",
      img: "https://images.pexels.com/photos/2724749/pexels-photo-2724749.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
    {
      id: 4654884,
      price: "800,0000",
      description: "منزل للبيع في ريف دمشق ,الغوطة الشرقية",
      layout: "120",
      bed: "1",
      bathroom: "4",
      date: 6,
      location: "  ريف دمشق, الغوطة الشرقية ",
      img: "https://images.pexels.com/photos/2079234/pexels-photo-2079234.jpeg?auto=compress&cs=tinysrgb&w=600",
    },
  ];
  export const carSale = [
    {
      id: 1,
      price: "90,0000",
      title: "فورد فيوجن  ",
      date: 2,
      speed: "25000",
      production: "2021",
      location: "",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRoRJ8RvC7P5QOumwfaPhPERZzmbasE-M3bBw&s",
    },
    {
      id: 2,
      price: "90,0000",
      title: "رينو اوسترال",
      date: 4,
      speed: "20000",
      production: "2020",
      location: "ريف دمشق, ببيلا",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMnq2APGr_l6dFxk5o5R26dGVy79IwTd2RLA&s",
    },
    {
      id: 3,
      price: "90,0000",
      title: "مازدا 6 نص فل خليجي 2025",
      date: 5,
      speed: "0",
      production: "2025",
      location: "دمشق, شارع بغداد",
      img: "https://alemaratcars.com/wp-content/uploads/2024/08/%D9%85%D8%A7%D8%B2%D8%AF%D8%A7-6-%D9%86%D8%B5-%D9%81%D9%84-2025.jpg",
    },
    {
      id: 4,
      price: "90,0000",
      title: "هيونداي سانتفيه",
      date: 7,
      speed: "70000",
      production: "2013",
      location: "دمشق, شارع خالد بن الوليد",
      img: "https://www.bankstreethyundai.com/vimgs/CAC30HYS041B021001/IOF_H600/2013-Hyundai-Santa-Fe-4dr-FWD-SWB_101.jpg",
    },
  ];
  